---
dependencies:
  - name: ui
    version: 1.0.0
    repository: https://raw.githubusercontent.com/czm41k/helm-charts/master
  - name: post
    version: 1.0.0
    repository: https://raw.githubusercontent.com/czm41k/helm-charts/master

  - name: comment
    version: 1.0.0
    repository: https://raw.githubusercontent.com/czm41k/helm-charts/master

  - name: mongodb
    version: 0.4.18
    repository: https://kubernetes-charts.storage.googleapis.com
...
